release workflows
q-shift/backstage-plugins pull request #51
Opened 2024-03-13 08:55 UTC by jacobdotcosta

2024-03-13 10:58 UTC, cmoulliard reviewed
I think that we need also a step to verify if the package(s) that we would like to publish part of a release do not yet exist on npmjs.org !

2024-03-13 11:08 UTC, jacobdotcosta commented
> I think that we need also a step to verify if the package(s) that we would like to publish part of a release do not yet exist on npmjs.org !

Do you mean check if packages with the same release number already exist on `npmjs.org`? There shouldn't be as this should be the only way of publishing the artifacts.

2024-03-13 12:41 UTC, cmoulliard commented
> Do you mean check if packages with the same release number already exist on `npmjs.org`? There shouldn't be as this should be the only way of publishing the artifacts.

Yes or locally. Why ? npmjs.org don't support anymore that we override a package already pushed as that was possible in the past

2024-03-13 14:04 UTC, jacobdotcosta commented
I have it but I'm not sure where to place the validation. Should it be placed on the first workflow to prevent the creation of the version PR tag?

2024-03-13 17:33 UTC, cmoulliard commented
> I have it but I'm not sure where to place the validation. Should it be placed on the first workflow to prevent the creation of the version PR tag?

That makes sense

2024-03-14 09:16 UTC, cmoulliard commented
Can you add a section to the README to explain what folks should do to trigger a new release ? @jacobdotcosta

2024-03-18 10:02 UTC, jacobdotcosta commented
Added a `RELEASE.md` file documenting the release process.

2024-03-18 11:42 UTC, cmoulliard commented on RELEASE.md
> +The release process is implemented on 3 GitHub actions.
"The release process is implemented on 3 GitHub actions." 
=>
"The release process is implemented by 3 GitHub actions."

2024-03-18 11:42 UTC, cmoulliard commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
I suppose that you would like to say here `Run manually the flow using the button "Run workflow" from the actions menu to generate a pull request with new versions to be released" ?
Question: Are the versions calculated automatically or should we let nevertheless the option to the user to provide them ?

2024-03-18 11:42 UTC, cmoulliard commented on RELEASE.md
> +Upon on the merge of the release PR this workflow will be treiggered which will:
"treiggered" => "triggered"

2024-03-18 11:42 UTC, cmoulliard commented on RELEASE.md
> +Automatic workflow, triggered by the GitHub release, that publishes the
Do we need this workflow vs having it merged with the `release` workflow ?

2024-03-18 14:03 UTC, jacobdotcosta commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
There's a dropdown for the user to select if it's a `fix`, a `minor` or a `major` release. This value is then passed to the [`npm version` command](https://docs.npmjs.com/cli/v10/commands/npm-version) which calculates the next version number.

2024-03-18 14:05 UTC, jacobdotcosta commented on RELEASE.md
> +Automatic workflow, triggered by the GitHub release, that publishes the
I decided not to change it as it was already done. One advantage of having it decoupled is that it could eventually be executed independently, although ATM the option is not activated.

2024-03-18 14:05 UTC, jacobdotcosta commented on RELEASE.md
> +Upon on the merge of the release PR this workflow will be treiggered which will:
fixed.

2024-03-18 14:05 UTC, jacobdotcosta commented on RELEASE.md
> +The release process is implemented on 3 GitHub actions.
fixed.

2024-03-19 07:52 UTC, cmoulliard commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
> There's a dropdown for the user to select

You mean a dropdown using github action like this https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs ?

2024-03-19 07:53 UTC, cmoulliard commented on RELEASE.md
> +Automatic workflow, triggered by the GitHub release, that publishes the
I will mark the conversation as resolved. If needed, we could change it later like also offer the option not activated yet

2024-03-19 09:02 UTC, jacobdotcosta commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
Yes, in this case the user will have to choose the release type between the options presented and the `npm version` command will calculate the version number.

2024-03-19 10:05 UTC, cmoulliard commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
That should be then documented. something like this then "Manual workflow that generates a PR with the version that the user will provide to the github action menu using value: fix, minor or major where default is: ??"

What is then the default "??" ?

2024-03-19 10:13 UTC, jacobdotcosta commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
The default I added is `patch`.

2024-03-19 10:22 UTC, jacobdotcosta commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
```bash
$ npm pkg get version
"1.0.0"
$ npm version patch --no-git-tag-version
v1.0.1
$ npm pkg get version
"1.0.1"
$ npm version patch --no-git-tag-version
v1.0.2
$ npm version minor --no-git-tag-version
v1.1.0
$ npm version major --no-git-tag-version
v2.0.0
```

2024-03-19 13:00 UTC, jacobdotcosta commented on RELEASE.md
> +Manual workflow that generates a PR with the versions that will be released.
Improved the docs.

2024-03-20 06:57 UTC, cmoulliard reviewed
The 3 git workflows include the following actions:
```
        - name: Build all plugins
          uses: ./.github/actions/build
          with:
            node_version: ${{ matrix.node-version }}

        - name: Verify dist files generated (*.d.ts)
          run: |
            ls -la plugins/*/dist
```
I think that only the flow `tag-for-release.yaml` should include them as it makes no sense to tag/release and push to npmjs.org if we cannot compile the typescript files, generate the javascript files

2024-03-20 06:57 UTC, cmoulliard commented on RELEASE.md
> +* [Update version and create Release PR](..github/workflows/tag-for-release.yaml): create release PR with artifact updated versions.
"create release PR with artifact updated versions." => "Build packages, bump the node package version to the next version and create a release PR."

2024-03-20 06:57 UTC, cmoulliard commented on RELEASE.md
> +* [Tag and create Release](..github/workflows/`release.yaml): create release
"create release " => "Tag the git repository and release it"

2024-03-20 06:57 UTC, cmoulliard commented on RELEASE.md
> +* [Publish packages to Node.js](..github/workflows/`npm-publish.yaml): publish artifacts to npmjs.org
"publish artifacts to npmjs.org" => "publish the packages on npmjs.org"

2024-03-20 07:55 UTC, jacobdotcosta commented
> The 3 git workflows include the following actions:
> 
> ```
>         - name: Build all plugins
>           uses: ./.github/actions/build
>           with:
>             node_version: ${{ matrix.node-version }}
> 
>         - name: Verify dist files generated (*.d.ts)
>           run: |
>             ls -la plugins/*/dist
> ```
> 
> I think that only the flow `tag-for-release.yaml` should include them as it makes no sense to tag/release and push to npmjs.org if we cannot compile the typescript files, generate the javascript files

I agree that the release workflow won't need this but are you sure the Publish workflow also doesn't need it? Won't it need the project to have been built in order to publish it to npmjs.org?

2024-03-20 07:58 UTC, jacobdotcosta commented on RELEASE.md
> +* [Update version and create Release PR](..github/workflows/tag-for-release.yaml): create release PR with artifact updated versions.
fixed.

2024-03-20 07:58 UTC, jacobdotcosta commented on RELEASE.md
> +* [Tag and create Release](..github/workflows/`release.yaml): create release
fixed

2024-03-20 07:59 UTC, jacobdotcosta commented on RELEASE.md
> +* [Publish packages to Node.js](..github/workflows/`npm-publish.yaml): publish artifacts to npmjs.org
fixed

2024-03-20 16:39 UTC, cmoulliard commented
> I agree that the release workflow won't need this but are you sure the Publish workflow also doesn't need it? Won't it need the project to have been built in order to publish it to npmjs.org?

As we don't save the artifacts built (= js files), then such a build is needed when we push on npmjs.org. Nevertheless, in order to tag the git repo, we should also do a `build` to be sure that project is in good health ;-)

2024-03-25 08:54 UTC, jacobdotcosta commented
> > I agree that the release workflow won't need this but are you sure the Publish workflow also doesn't need it? Won't it need the project to have been built in order to publish it to npmjs.org?
> 
> As we don't save the artifacts built (= js files), then such a build is needed when we push on npmjs.org. Nevertheless, in order to tag the git repo, we should also do a `build` to be sure that project is in good health ;-)

Great, so I'll leave this as is.

2024-03-25 09:09 UTC, cmoulliard commented
> Great, so I'll leave this as is.

No. Here is what we should do concerning the existing jobs @jacobdotcosta 

- tag-for-release.yaml: build nodejs plugins as it makes no sense to tag and create a PR if current code cannot be compiled (= tsc) and build (= generate js artifacts). This job should be renamed as we don't tag it (from git point of view) BUT we bump the nodejs packager version and create a PR
- release.yaml: Remove nodejs build step (as this has been done by the previous job creating the PR). Rename the title from `release` to `tag-and-create-release`
- npm-publish: build nodejs artfifacts (= yanr tsc; yarn build) FROM the git tagged repository, publish on npmjs.org

2024-03-25 09:54 UTC, cmoulliard requested changes
2 remarks:
- Remove the step to install yarn part of the `tag-and-create-release.yaml` as we don't need it
- Dont forget to also update the README file as you renamed the files. Check also the description of what each job do

2024-03-25 11:02 UTC, jacobdotcosta commented
Made several improvements to the docs. Could you take another look @cmoulliard ?

2024-03-25 13:25 UTC, cmoulliard approved these changes, later dismissed
See small change

2024-03-25 13:25 UTC, cmoulliard commented on RELEASE.md
>   This workflow will
This workflow will execute the following command `npm version` to calculate the new version of the plugins.

2024-03-25 13:55 UTC, jacobdotcosta commented on RELEASE.md
>   This workflow will
I improved the description using an alternate description. @cmoulliard

2024-03-25 14:31 UTC, cmoulliard approved these changes

2024-03-25 14:33 UTC, merged